[workspace]
resolver = "2"

members = ["arceos-vmm"]

[profile.release]
lto = true

[workspace.dependencies]
# axstd = { git = "https://github.com/arceos-hypervisor/arceos.git", branch = "vmm_inject_interrupt", features = ["ipi", "smp"] }
axstd = { path = "../arceos/ulib/axstd", features = ["ipi", "smp"]}
# axvm = { git = "https://github.com/arceos-hypervisor/axvm.git", branch = "inject_interrupt" }
axvm = { path = "../axvm" }
# axvcpu = { git = "https://github.com/arceos-hypervisor/axvcpu.git", branch = "inject_interrupt" }
axvcpu = { path = "../axvcpu" }
axaddrspace = { git = "https://github.com/arceos-hypervisor/axaddrspace.git", branch = "inject_interrupt" }
