[workspace]
resolver = "2"

members = ["arceos-vmm"]

[profile.release]
lto = true

[workspace.dependencies]
axstd = { git = "https://github.com/arceos-hypervisor/arceos.git", branch = "vmm_rebase" }
axconfig = { git = "https://github.com/arceos-hypervisor/arceos.git", branch = "vmm_rebase" }

axvm = { git = "https://github.com/arceos-hypervisor/axvm.git", branch = "edition2024" }
axvcpu = { git = "https://github.com/arceos-hypervisor/axvcpu.git", branch = "update_toolchain" }
axaddrspace = { git = "https://github.com/arceos-hypervisor/axaddrspace.git", branch = "update_toolchain" }

# [patch."https://github.com/arceos-hypervisor/arceos.git"]
# axstd = { path = "../arceos/ulib/axstd" }

# [patch."https://github.com/arceos-hypervisor/axvm.git"]
# axvm = { path = "../arceos-crates/axvm" }

# [patch."https://github.com/arceos-hypervisor/axvcpu.git"]
# axvcpu = { path = "../arceos-crates/axvcpu" }

# [patch."https://github.com/arceos-hypervisor/axaddrspace.git"]
# axaddrspace = { path = "../arceos-crates/axaddrspace" }

# [patch."https://github.com/arceos-hypervisor/x86_vcpu.git"]
# x86_vcpu = { path = "../arceos-crates/x86_vcpu" }

# [patch."https://github.com/arceos-hypervisor/arm_vcpu.git"]
# arm_vcpu = { path = "../arceos-crates/arm_vcpu" }

# [patch."https://github.com/arceos-hypervisor/riscv_vcpu.git"]
# riscv_vcpu = { path = "../arceos-crates/riscv_vcpu" }