[workspace]
resolver = "2"

members = ["arceos-vmm"]

[profile.release]
lto = true

[workspace.dependencies]
axstd = { git = "https://github.com/arceos-hypervisor/arceos.git", branch = "vmm" }

axvm = { git = "https://github.com/arceos-hypervisor/axvm.git" }
axvcpu = { git = "https://github.com/arceos-hypervisor/axvcpu.git" }
axaddrspace = { git = "https://github.com/arceos-hypervisor/axaddrspace.git" }

[patch."https://github.com/arceos-hypervisor/arceos.git"]
axstd = { path = "../arceos/ulib/axstd" }

[patch."https://github.com/arceos-hypervisor/axvm.git"]
axvm = { path = "../arceos-crates/axvm" }

[patch."https://github.com/arceos-hypervisor/axaddrspace.git"]
axaddrspace = { path = "../arceos-crates/axaddrspace" }

[patch."https://github.com/arceos-hypervisor/arm_vcpu.git"]
arm_vcpu = { path = "../arceos-crates/arm_vcpu" }

[patch."https://github.com/arceos-org/allocator.git"]
allocator = { path = "../arceos-crates/allocator" }
